### PR TITLE
Fixed issue with listing all documents

### PR DESCRIPTION
**Pull request by amala-james-cko**
Hey @ReeceM ,
Thank you for adding the access token, it worked like a charm. But when creating `sitemap.xml` it was showing all the links from prismic. So I made a small change to your code in generator.js.

Would you mind taking a look at it and if it's okay can you merge it?

### CODE REVIEW

**Comment by ReeceM** [comment]
Hey @amala-james-cko,

Thank you for making a PR, I will look at it also locally. The test passed so that's good. 👍 

If you could, would you be able to add an example below of what it gave before and then after the change? Doesn't have to be exact to what you had, the links/text can be redacted.

**Review by ReeceM — CHANGES_REQUESTED** [review]
Hi @amala-james-cko, I am not sure if the review requests were submitted yesterday. I don't think I clicked finish then.

There are a few things that have changed as you said, overall there isn't much difference in the functionality added by using the `Prismic.Predicates.at` and looping or using the `Prismic.Predicates.any`, the other thing is that if there is more than 20 total docs, then the results need to be paginated properly.

Is it possible to give an example of what you meant by <q>showing all the links from prismic</q>.

**Comment by ReeceM** [comment]
> Hi @amala-james-cko, I am not sure if the review requests were submitted yesterday. I don't think I clicked finish then.
> 
> There are a few things that have changed as you said, overall there isn't much difference in the functionality added by using the `Prismic.Predicates.at` and looping or using the `Prismic.Predicates.any`, the other thing is that if there is more than 20 total docs, then the results need to be paginated properly.
> 
> Is it possible to give an example of what you meant by showing all the links from prismic.

Yeah, I hadn't clicked finish on the review panel. I was thought it had been sent through, I hadn't missed the PR.

**Comment by amala-james-cko** [comment]
Closing it since the use case is different.

**Comment by ReeceM** [comment]
> Closing it since the use case is different.

Hi, the use case of the PR or the package?

The PR is adding improved functionality which is fine

**Pull request closed without merging**
